apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-progress-or
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
