apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-router
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-router
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
      - name: web-router-config
        configMap:
          name: web-router-config
      - name: web-router-favicon
        configMap:
          name: web-router-favicon
      containers:
      - name: caddy
        image: hinst/orange-caddy
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-router-config
          mountPath: /etc/caddy
        - name: web-router-favicon
          mountPath: /usr/share/caddy/favicon
        resources:
          limits:
            cpu: 1
            memory: 200Mi
