apiVersion: batch/v1
kind: CronJob
metadata:
  name: downloader
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: smart-progress-or
          containers:
          - name: downloader
            image: hinst/smart-progress-do-downloader:latest
            imagePullPolicy: Always
            volumeMounts:
              - name: data
                mountPath: /app/data
            env:
              - name: goalId
                valueFrom:
                  configMapKeyRef:
                    name: downloader-config
                    key: goalId
          restartPolicy: Never
