apiVersion: v1
kind: Service
metadata:
  name: web-router
  labels:
    app: web-router
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: web-router