apiVersion: v1
kind: Namespace
metadata:
  name: smart-progress-or
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smart-progress-or
  namespace: smart-progress-or
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/orangepi/App/smart-progress-or
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-progress-or
  namespace: smart-progress-or
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
