apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-router
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-router
    spec:
      volumes:
      - name: web-router-config
        configMap:
          name: web-router-config
      containers:
      - name: caddy
        image: hinst/orange-caddy
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-router-config
          mountPath: /etc/caddy
---
apiVersion: v1
kind: Service
metadata:
  name: web-router
  labels:
    app: web-router
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: web-router
