apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  labels:
    app: web-ui
  namespace: smart-progress-or
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-ui
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: smart-progress-or-web-ui
        image: hinst/smart-progress-or-web-ui:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /smartProgress-or
            port: 8080
          periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  labels:
    app: web-ui
  namespace: smart-progress-or
spec:
  ports:
  - port: 8080
  selector:
    app: web-ui
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-progress-or
  namespace: smart-progress-or
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi