apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  labels:
    app: web-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-ui
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: smart-progress-or
      containers:
      - name: smart-progress-or-web-ui
        image: hinst/smart-progress-or-web-ui:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /smartProgress-or
            port: 8080
          periodSeconds: 60
        volumeMounts:
          - name: data
            mountPath: /app/data
            readOnly: true
        resources:
          requests:
            cpu: 1m
            memory: 1
          limits:
            cpu: 1
            memory: 100Mi
